### ISSUE TITLE
`npm run dev` vs `next`

### ISSUE THREAD

**Issue by html5cat** [zeit/learnnextjs-content#79]
Curious why you prefer `npm run dev` vs `next`. Imho `next` is shorter and more elegant 😄 
https://github.com/arunoda/learnnextjs-content/blob/dd115eac25cda880c292fa19461341760b54ad11/content/1-basics/1-getting-started.js#L77

**Comment by timneutkens** [comment]
Hey @html5cat, the reason for this is that it's almost always guaranteed to be the local version of `next` instead of the global version if the user doesn't have `./node_modules/.bin` in their `$PATH`. It prevents inconsistencies between versions.
